# Define environment groups - one for API, one for Worker
envVarGroups:
  # API environment variables
  - name: agentic-outreach-api-env
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_BASE_URL
        value: https://openrouter.ai/api/v1
      - key: AGENTOPS_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: ES256
      - key: CORS_ORIGINS
        value: "*"
      - key: APP_NAME
        value: "Agentic Outreach API"
  
  # Worker environment variables
  - name: agentic-outreach-worker-env
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_BASE_URL
        value: https://openrouter.ai/api/v1
      - key: AGENTOPS_API_KEY
        sync: false
      - key: APP_NAME
        value: "Agentic Outreach Worker"

services:
  # Production Web Service - FastAPI API
  - type: web
    name: agentic-outreach-api
    runtime: python
    region: frankfurt
    plan: starter
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - fromGroup: agentic-outreach-api-env
      - key: DEBUG
        value: false
    autoDeploy: true
    healthCheckPath: /health

  # Dev Web Service - FastAPI API
  - type: web
    name: agentic-outreach-api-dev
    runtime: python
    region: frankfurt
    plan: free
    branch: dev
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT --reload
    envVars:
      - fromGroup: agentic-outreach-api-env
      - key: DEBUG
        value: true
    autoDeploy: true
    healthCheckPath: /health

  # Production Background Worker Service
  - type: worker
    name: agentic-outreach-worker
    runtime: python
    region: frankfurt
    plan: starter
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.background.render_worker
    envVars:
      - fromGroup: agentic-outreach-worker-env
      - key: DEBUG
        value: false
    autoDeploy: true

  # Dev Background Worker Service
  - type: worker
    name: agentic-outreach-worker-dev
    runtime: python
    region: frankfurt
    plan: free
    branch: dev
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.background.render_worker
    envVars:
      - fromGroup: agentic-outreach-worker-env
      - key: DEBUG
        value: true
    autoDeploy: true