# Deploy Frontend to Production using Option 3: Pass environment variables via CLI
# This workflow deploys the frontend to Vercel with environment variables passed
# directly through the Vercel CLI using -e flags, giving us full control

name: Deploy Frontend to Production

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Debug - Check file structure
        working-directory: ./frontend
        run: |
          echo "Current directory:"
          pwd
          echo -e "\nDirectory structure:"
          ls -la
          echo -e "\nlib directory:"
          ls -la lib/
          echo -e "\ntsconfig.json content:"
          cat tsconfig.json
          echo -e "\nChecking if files exist:"
          test -f lib/supabase/client.ts && echo "lib/supabase/client.ts exists" || echo "lib/supabase/client.ts NOT FOUND"
          test -f lib/utils.ts && echo "lib/utils.ts exists" || echo "lib/utils.ts NOT FOUND"

      - name: Run type checking
        working-directory: ./frontend
        run: npm run type-check

      - name: Build application locally for testing
        working-directory: ./frontend
        run: npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Debug - Check token availability
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [ -z "$VERCEL_TOKEN" ]; then
            echo "VERCEL_TOKEN is not set!"
            exit 1
          else
            echo "VERCEL_TOKEN is available (hidden)"
          fi

      - name: Deploy to Vercel
        run: |
          # Create a new deployment from scratch
          cd frontend
          
          # Remove any existing .vercel directory to start fresh
          rm -rf .vercel
          
          # Deploy as a new project, ignoring the misconfigured one
          vercel --prod \
            --token="${{ secrets.VERCEL_TOKEN }}" \
            --env NEXT_PUBLIC_SUPABASE_URL="${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" \
            --env NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY="${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY }}" \
            --yes \
            --force \
            --public \
            > deployment-url.txt
          
          # Output deployment URL
          echo "Deployment URL: $(cat deployment-url.txt)"
          echo "deployment_url=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT
        id: deploy

      - name: Comment deployment status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const deploymentUrl = '${{ steps.deploy.outputs.deployment_url }}';
            const status = '${{ job.status }}';
            const commit_sha = context.sha;
            
            const body = status === 'success' 
              ? `✅ Frontend deployed to production: ${deploymentUrl}`
              : `❌ Frontend deployment failed. Check the [workflow logs](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`;
            
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commit_sha,
              body: body
            });